- name: playbook name is nginx install and start nginx
  hosts: frontend 
  become: yes #ila isthe sudo access istunnam ani ardham
  tasks:
  - name: 1st task is installing nginx 
    ansible.builtin.package: 
      name: nginx 
      state: present #ila isthe install cheyyamani 

  - name: 2nd task is start nginx 
    ansible.builtin.service: 
      name: nginx 
      state: started 
      enabled: yes #enable cheyyamani


# ansible.builtin.package ki
#present ---> insatll cheyyamani
#absent ----> remove cheyyamani 


# ansible.builtin.service ki 
#started ----> start cheyyamani
#stopped ----> stop cheyyamani
#restarted ----> restart cheyyamani
#reloaded ----> reload cheyyamani 
#enabled: yes ani isthe enable avutundhi


# e playbook dwara manam server ni touch cheyyakunda nginx ni install chesaam.nginx ni run chesaam.



