- name: variables from prompt 
  hosts: local 
  connection: local 
  vars_prompt: 
  - name: USERNAME #manam enter chese value ikkadiki vachi store avutundhi
    prompt: please enter your username 
    private: true #ila isthe manam enter chesedhi kanipinchadhu 

  - name: PASSWORD 
    prompt: please enter your password 
    private: true 

  tasks: 
  - name: printing the user information 
    ansible.builtin.debug:
      msg: "Hello username is {{ USERNAME }}, password is {{ PASSWORD }}"     