- name: playbook name is variables from inventory
  hosts: local 
  connection: local 
  tasks: 
  - name: printing course information 
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}" 


#ansible-playbook -i inventory.ini 11-arguments.yaml -e "COURSE=ARGUMENTS" -e "DURATION=10mins" -e "TRAINER=Sivakumar" 
# variables ni command line nunchi pass chestunnam      