- name: understanding vars preference 
  hosts: local 
  connection: local 
  # vars: 
  #   GREETING: "Hello from PLAY"
  # vars_files: 
  # - course.yaml 
  # vars_prompt: 
  # - name: GREETING 
  #   prompt: please enter the Greeting 
  #   private: false #ila isthe manam enter chesindhi manaki kanipistundi 
  tasks: 
  - name: print the greeting 
    # vars:
    #   GREETING: "Hello from TASK"
    ansible.builtin.debug: 
      msg: "{{ GREETING }}"   

#variable preference order:
# 1. COMMAND LINE lo manam pass chesina arguments
# 2. TASK variable  
# 3. FILE lo define chesina variable
# 4. PROMPT lo ichina variable 
# 5. PLAY level variable     
# 6. INVENTORY lo ichina variable  