- name: conditions demo 
  hosts: local 
  connection: local 
  vars: 
    NUMBER: 78 
  tasks: 
  - name: print if a number is lessthan or equal to 100 
    ansible.builtin.debug: 
      msg: "Given number {{ NUMBER }} is lessthan or equal to 100" 
    when: NUMBER < 100   

  - name: print if a number is greaterthan 100 
    ansible.builtin.debug: 
      msg: "Given number {{ NUMBER }} is greaterthan 100" 
    when: NUMBER > 100   