- name: functions 
  hosts: local 
  connection: local 
  vars: 
    PERSONS: "Ramesh,Suresh,Raheem,Joseph"
  tasks: 
  - name: check undefined variable 
    ansible.builtin.debug: 
      msg: "Hello {{ PERSON | default('Ramesh') }}"  # PERSON ni ekkadina define chesthe aaa value teeskuntundi. okavela define cheyyakapothe default ga ramesh ani teeskuntundhi. 

  - name: print names 
    ansible.builtin.debug: 
      msg: "Hello {{ PERSONS | split(',') }}"  # split function. cama use chesi split cheyyamani cheptunnam. 

  - name: convert map into list 
    vars: 
      course: 
        name: ansible 
        duration: 10Hrs 
        trainer: sivakumar 
    ansible.builtin.debug: 
      msg: "Course info: {{ course | dict2items }}"  # Map nunchi List ki convert chestundhi. 


 #  "msg": "Course info: [{'key': 'name', 'value': 'ansible'}, {'key': 'duration', 'value': '10Hrs'}, {'key': 'trainer', 'value': 'sivakumar'}]"        

  - name: convert list into map  
    vars: 
      course: 
      - {'key': 'name', 'value': 'ansible'} 
      - {'key': 'duration', 'value': '10Hrs'} 
      - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug: 
      msg: "Course info: {{ course | items2dict }}" 

#  "msg": "Course info: {'name': 'ansible', 'duration': '10Hrs', 'trainer': 'sivakumar'}"  

  - name: convert to UPPER CASE 
    vars:
      name: "Sivakumar Reddy M" 
    ansible.builtin.debug: 
      msg: "Hello {{ name | upper }}"   

  - name: convert to LOWER CASE 
    vars:
      name: "SIVAKUMAR Reddy M" 
    ansible.builtin.debug: 
      msg: "Hello {{ name | lower }}"    

  - name: check IP address is valid or not 
    vars: 
      ip: "300.300.300.300" 
    ansible.builtin.debug: 
      msg: "{{ ip | ansible.utils.ipaddr }}"       



            


