- name: functions 
  hosts: local 
  connection: local 
  vars: 
    PERSONS: "Ramesh,Suresh,Raheem,Joseph"
  tasks: 
  - name: check undefined variable 
    ansible.builtin.debug: 
      msg: "Hello {{ PERSON | default('Ramesh') }}"  # PERSON ni ekkadina define chesthe aaa value teeskuntundi. okavela define cheyyakapothe default ga ramesh ani teeskuntundhi. 

  - name: print names 
    ansible.builtin.debug: 
      msg: "Hello {{ PERSONS | split(',') }}"  # split function. cama use chesi split cheyyamani cheptunnam. 

  - name: convert map into list 
    vars: 
      course: 
        name: ansible 
        duration: 10Hrs 
        trainer: sivakumar 
    ansible.builtin.debug: 
      msg: "Course info: {{ course | dict2items }}"  # Map nunchi List ki convert chestundhi.        


