- name: functions 
  hosts: local 
  connection: local 
  tasks: 
  - name: check undefined variable 
    ansible.builtin.debug: 
      msg: "Hello {{ PERSON | default('Ramesh') }}"  # PERSON ni ekkadina define chesthe aaa value teeskuntundi. okavela define cheyyakapothe default ga ramesh ani teeskuntundhi. 
      