- name: user creation # Imagine there is no user module in ansible 
  hosts: local 
  connection: local 
  tasks: 
  - name: check roboshop user exist or not 
    ansible.builtin.command: id roboshop 
    register: output 
    ignore_errors: true 

  - name: create user 
    ansible.builtin.command: useradd roboshop 
    when: output.rc != 0 # it means above task is failure 

  - name: user already exist 
    ansible.builtin.debug: 
      msg: "roboshop user already exist"   
