- name: user creation # Imagine there is no user module in ansible 
  hosts: local 
  connection: local 
  tasks: 
  - name: check roboshop user exist or not 
    ansible.builtin.command: id roboshop 