- name: create ec2 and route53-records 
  hosts: local 
  connection: local 
  vars: 
    instances: 
    - mysql 
    - backend 
    - frontend 
    subnet_id: subnet-0d9417ad307d71b73 
    sg_id: sg-041eee2885a103497
  tasks:
  - name: create ec2-instances 
    amazon.aws.ec2_instance: 
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro 
      security_group: "{{ sg_id }}" 
      image_id: ami-09c813fb71547fc4f 
      tags:
        name: "{{ item }}"
    loop: "{{ instances }}"  

